#! /usr/bin/env python
# -*- coding: utf-8 -*-

import sys
sys.path.append('./src')

from board import Color, Coordinate
from player import iPlayer
from cplayer import *
from game import OthelloGame

def select_opponent():
    while True:
        print("Select Opponent Player :")
        print("   RandomPlayer(0)")
        print("   FirstOrderPlayer(1)")
        print("   MinimumPlayer(2)")
        print("> ", end='')
        instr = input()
        if instr == '0':
            return RandomPlayer
        if instr == '1':
            return FirstOrderPlayer
        if instr == '2':
            return MinimumPlayer

def select_color():
    while True:
        print("Select Your Color : Black(0) or White(1)")
        print("> ", end='')
        instr = input()
        if instr == '0':
            return Color.BLACK
        if instr == '1':
            return Color.WHITE

def main():
    game = OthelloGame()
    try:
        OPPONENT_CLS = select_opponent()
        color = select_color()
    except KeyboardInterrupt:
        sys.exit(1)
    except Exception as e:
        print(e)
        sys.exit(2)
    player = iPlayer("Player", color)
    opponent = OPPONENT_CLS("CP", Color.opponent(color))

    game.register_player(player)
    game.register_player(opponent)

    game.start()


if __name__ == '__main__':
    main()
