#! /usr/bin/env python
# -*- coding: utf-8 -*-

import sys
sys.path.append('./src')

from board import Color, Coordinate
from player import iPlayer
from game import OthelloGame

def main():
    game = OthelloGame()
    player_black = iPlayer("Player", Color.BLACK)
    player_white = iPlayer("CP", Color.WHITE)

    game.register_player(player_black)
    game.register_player(player_white)

    game.start()


if __name__ == '__main__':
    main()
